- src/articles/speed-up-with-browserslist/index.md
- src/styles/blocks/content.css
Добавляет базовые стили для таблиц в контенте.
> Добавляет стили для таблиц контента

- src/includes/article-card.njk
- src/layouts/article.njk
- src/styles/blocks/article-card.css
- src/styles/blocks/articles.css
- src/styles/blocks/authors.css
Изначально ссылка на статью была только в заголовке карточки, что плохо сказывается на UX. Сделал карточку полностью ссылкой. Так же самой статье сделал одной ссылкой аватарку и имя автора.
> Делает карточку статьи одной ссылкой

- src/layouts/article.njk
Fix #21 
Заменил адрес старого репозитория на новый.
> Правит ссылку на редактирование статьи

- src/styles/blocks/content.css
Fix #6 
Установил семейство шрифтов для блоков кода в статьях.
> Устанавливает шрифт для блоков кода

- src/styles/blocks/article-card.css
- src/styles/blocks/article.css
- src/styles/blocks/authors.css
- src/styles/blocks/content.css
- src/styles/blocks/footer.css
- src/styles/blocks/links.css
- src/styles/blocks/navigation.css
Fix #11 
Увеличил размер всего текста для мобильных устройств до 16px.
> Увеличивает размер шрифта для мобильных

- src/pages/index.njk
Fix #17 
Добавил скрытые заголовки h1 и h2 для главной страницы.
> Добавляет заголовки для главной страницы

- src/layouts/article.njk
Fixes #4.
Добавляет микроразметку на страницу статьи в соответствии с https://schema.org/Article
> Добавляет микроразметку Article на страницу статьи #4

- src/styles/blocks/article-card.css
Fix #43
Недоделки с прошлых изменений автарок :(
> Исправляет размер аватарок на мини-карточках

- src/styles/blocks/content.css
- Теперь внутри figure картинкам тоже нормально
- У figure теперь есть базовые стили
- Инлайновый код выводится правильным шрифтом
- У блоков стилей есть одинаковые заглавия
> Правит картинки и причёсывает форматирование

- src/includes/article-card.njk
- src/styles/blocks/article-card.css
- src/styles/blocks/articles.css
> Подгружать картинку из статьи в превью на главной странице #9

- src/styles/blocks/authors.css
- src/styles/blocks/content.css
> Повышает контрастность посещённых сcылок

- gulpfile.js
- package-lock.json
- package.json
> Добавляет кеш-бастинг #14

- src/styles/blocks/article.css
- src/styles/blocks/box-sizing.css
- src/styles/blocks/content.css
- src/styles/blocks/links.css
- src/styles/blocks/navigation.css
- src/styles/styles.css
Fix #79 
Проверил на всех разрешениях, вроде ничего не поломалось.
> Добавляет box-sizing

- src/styles/blocks/creators.css
Fix #84 
Заодно у переводчиков и редакторов убралось.
> Убирает фантомную ссылку

- src/styles/blocks/article.css
> Меняет поведение якоря, покзывая его по ховеру или фокусу #83

- src/articles/speed-up-with-browserslist/index.md
> Ускоряемся с помощью Browserslist: исправляет фактическую ошибку в тексте.

- src/styles/blocks/content.css
- src/styles/styles.css
> Стилизует скроллбар

- src/articles/details-summary-elements/index.md
Привет,
Небольшая правка для blockquote.
> Исправляет опечатку в закрытии тега

- package-lock.json
Попытка зарезолвить уязвимости в npm-пакетах.
Информация о обновлении тут: #130
> Обновление npm-пакетов

- package.json
Заменил deprecated правила, исправил некоторые ошибки.
> Фиксит правила stylelint

- src/articles/contenteditable/index.md
> Закрывающие теги для цитат, скрол для блока с contenteditable

- src/includes/article-card.njk
> [105] Добавляет itemscope к article-card

- src/feed/articles.njk
> Удаляем верстку с кнопкой скопировать из RSS фида

- .github/workflows/deploy.yml
Немного улучшений в синтаксис пайплайна деплоя
> Update deploy pipeline script

- src/styles/blocks/menu.css
> Правит отступы в шапке для Safari

- .eleventy.js
- src/articles/articles.11tydata.js
- src/layouts/article.njk
Продолжает серию рефакторинга по переносу вычислений из шаблонов в data-файлы. На этот раз - дополнительные статьи. Под них заведено отдельное computed-свойство и удалён nunjucks-фильтр.
> Перенос вычисления дополнительных статей из блока "ещё" в data-файл

- src/includes/aside.njk
> Недочепятка

- src/includes/open-graph.njk
- src/pages/episode.njk
Небольшие исправления og:meta для улучшения превью в Телеграме и социальных сетях.
> Исправляет og:meta

- src/people/artem-plaksin/index.md
Все-таки мое имя пишется через "е". Могу паспорт показать.
> Добавляет е

- .stylelintrc.json
- src/styles/blocks/podcast.css
Решает [#263](https://github.com/web-standards-ru/web-standards.ru/issues/263)
> Добавляет тень плееру подкаста

- .eleventy.js
- src/helpers/podcasts-service.js
- src/pages/episode.njk
- src/scripts/modules/podcast.js
- src/styles/blocks/page.css
- src/styles/blocks/podcast.css
- кнопки с временными метками переделаны на ссылки
- добавлены id для заголовков, чтобы можно было скроллить до нужных блоков, нажимая на ссылки
- подправлена логика установки времени при загрузке страницы:  у аудио может быть ещё не загружена метаинформация и установка времени сработает некорректно.
> Добавляет id на заголовки на странице выпуска подкаста для возможности скролла к ним

- package.json
В 2-ой версии Eleventy появился incremental-режим. Поможет тем, кто пишет статьи и тут же хочет посмотреть, как они выглядят на самом сайте. При редактировании md-файла в dev-режиме будет собираться только он, а не все статьи.
> Добавляет incremental-режим

- src/scripts/modules/podcast.js
Правки:
- Переносит функцию `rewindAudio` выше по коду
- Инициализирует обработку кликов только на странице подкаста, иначе возникает ошибка на других страницах
> Правит инициализацию перемотки в подкасте

- src/styles/blocks/article-card.css
- src/styles/blocks/blob.css
Правки:
- Уменьшает дублирование стилей для задания маски `blob` с помощью custom properties
- Переносит задание `position: relative` с `.article-card__avatar` на `.blob`, чтобы это лучше соответствовало принципам БЭМ: элемент `.blob__photo` имеет абсолютное позиционирование, поэтому `position: relative;` должно быть на родительском блоке.
> Рефакторит компонент `blob`

- src/includes/header.njk
- src/pages/index.11tydata.js
- src/styles/blocks/header.css
- src/styles/blocks/informer.css
- src/styles/styles.css
Resolve #338
<details>
<summary>Скрины</summary>
<hr>
<hr>
</details>
> Добавляет информер о последнем выпуске подкаста

- eleventy.config.js
- package-lock.json
- package.json
Fix: #25. 
Fix: #31. 
Closes: #205 
Для реализации использовал [Elventy Image](https://www.11ty.dev/docs/plugins/image/), [механизм трансформаций](https://www.11ty.dev/docs/config/#transforms) и библиотеку [LinkeDOM](https://github.com/WebReflection/linkedom) для преобразований HTML на основе DOM API.
Для основого целевого формата выбрал webp, так как более современный avif медленее в кодировании/декодировании. Также оставляется оригинальный формат.
Атрибут `sizes` выглядит так:
```
(min-width: 1920px) calc((1920px - 2 * 64px) * 5 / 8 - 2 * 16px),
(min-width: 1240px) calc((100vw - 2 * 64px) * 5 / 8 - 2 * 16px),
(min-width: 700px) calc(700px - 2 * 16px),
calc(100vw - 2 * 16px)
```
Размеры изображений - оригинал, 600, 1200, 2400.
Уже есть [аналогичный …
> Добавляет оптимизацию изображений

- src/pages/episode.njk
- src/styles/blocks/podcast.css
fixes https://github.com/web-standards-ru/podcast/issues/22
> Переносит запятую из стилей в разметку

- src/styles/blocks/article.css
- src/styles/blocks/content.css
> Правит селектор для буквицы

- .github/workflows/deploy.yml
При создании PR срабатывает deploy action, чего быть не должно
> Правит условия деплоя
