src/styles/blocks/page.css
Если у пользователя в настройках ОС установлено пожелание не использовать анимации, определять это с помощью медиа выражения `prefers-reduce-motion: reduce` и выключать анимацию.
=> Добавлен prefers-reduce-motion в мобильное меню

src/articles/speed-up-with-browserslist/index.md, src/styles/blocks/content.css
Данные будет удобнее считывать и сравнивать, если распределить их в таблице немного по-другому: например, скорее всего читатель захочет сравнить размер сжатого бандла с плагином и без, поэтому если поставить две сравниваемые метрики одну под другой, не надо будет их искать в разных частях таблицы.
=> Меняет представление данных в таблице к статье о Browserslist

src/styles/blocks/content.css, src/styles/blocks/video.css
При загрузке видео `iframe` цеплял стили из `content.css` с минимальной высотой в `400px` и наезжал на нижние блоки с текстом.
До загрузки: 
После:
Поправил селекторы, добавил отступ сверху, получилось так:
=> Правит блок с видео при загрузке

src/styles/blocks/article.css
Fix #30 
Уменьшил ширину боковой части контента и увеличил ширину самой статьи.
Было (разрешение 2560px):
Стало (разрешение 2560px):
=> Изменяет сетку статьи

src/layouts/page.njk, src/styles/blocks/navigation.css, src/styles/styles.css
Fix #24 
Изменил цвет ссылок меню.
Переменная `--color-blue-medium` нигде не использовалась, поэтому заменил цвет в ней, чтобы не создавать новую (и цвет `#377db3` явно светлее, чем `#26649f`).
=> Изменяет цвет ссылок в меню

src/styles/blocks/articles.css
Сделал отображение дополнительных статей чуть красивее на разрешении 800+
Было: 
Стало:
=> Исправляет отображение дополнительных статей на мобильных

src/styles/blocks/content.css
Из-за того, что мы сделали контрастный цвет посещённых ссылок, они слились с текстом. К тому же у нас все ссылки потихоньку возвращаются в исходное состояние.
_Было:_
_Стало:_
=> Подчёркивает все ссылки в статье

src/scripts/scripts.js
Сейчас на кнопке меню `aria-label="Открыть меню"` вне зависимости от его состояния. Сделал так, чтобы при закрытом меню было `Открыть меню`, а при открытом `Закрыть меню`.
=> Делает aria-label в меню переключаемым

src/includes/article-card.njk, src/layouts/article.njk
Fixes #85 
Что сделал: перед выводом карточек статей в блоке "Ещё" создал переменную `articleCardVariant` со значением `related`.
В `article-card` собственно проверяю на это значение, логика с featured выполняется только если этого значения нет.
Не знаю насколько это костыльно и вообще правильно, но беглая проверка не выявила проблем
=> Исправляет отображение карточек related статей #85

.eleventy.js, src/styles/blocks/content.css
Fixes #56 
Disclaimer: У меня совсем мало опыта со генераторами статических сайтов, с Eleventy познакомился только у вас в проекте. Поэтому я могу неправильно понимать какие-то концепции его использования.
Столкнувшись с необходимостью добавить атрибут `tabindex` к тегу `code`, я пробовал `config.addFilter('markdown' ...`, однако никакого эффекта он не вызывал. Насколько я понял, этот фильтр сейчас вообще не используется.
В документации увидел способ подключения `markdown-it`, которым и воспользовался.
В контексте добавления атрибута именно к тегу `code`, подумал, что легче будет воспользоваться колбэком `highlight`.
На текущем этапе все работает, однако хочу убедиться, что строкой `config.setLibrary('md', md);` я ничего не должен был сломать. Со своей стороны я проверил несколько статей …
=> Позволяет выделять весь код в статьях

src/styles/blocks/navigation.css
Попытка починить #113 
Мне показалось безсмыссленным изпользование fixed для logo поэтому его позиционирование изменено на absolute.
А враперу добавлены свойства position: relative и width: 100%, чтобы он всегда сохранял максимальную ширину и не становился больше чем vieport.
Если в fixed был какой-то особый смысл commets pls.
=> Фикс неправильного поведения верстки при смене портретного режима на ландшафтный

src/styles/blocks/content.css
Сделал стили изображений и видео в статьях менее хрупкими (#155):
- убрал жёсткую привяку к непосредственному родителю;
- обнулил боковые отступы на десктопах.
Поясню про отступы, ибо это решение может быть спорным.
Растягивать небольшие изображения на всю контентную ширину не очень хорошо, будет мыло пиксельное. А прежний стиль `margin: 60px 0 60px auto;` медиа-контент шириной меньшей ширины контентной колонки прибивал к правому краю. При больших медиа оно ещё нормально смотрится, но вот с маленькими в купе с выравниванием текста влево выглядит кособоко: картинка/видео будто вырваны из текста вправо, но не полностью, на выноску не тянет.
В макете для меньших изображений нашёл только вариант, когда они зафлоачены вправо. С флоатом они нормально бы смотрелись, не оторваными.
Если же в …
=> Исправление стилей медиа-контента

src/scripts/modules/copy-link.js
Фикс #169 
Вырезаем хэш из текущего url.
Кэш должен удаляться безопасно так как всегда начинается с `#`
=> Убираем предыдущий хэш из ссылки перед копированием

.eleventy.js, src/articles/articles.11tydata.js, src/includes/article-card.njk, src/layouts/article.njk
Сейчас для извлечения данных о людях в статьях используется nunjucks-фильтр `filterPeople `, например:
```nunjucks
{%- for translator in collections.people | filterPeople(translators) -%}
```
Это все равно что делать запросы в базу данных из шаблонизатора.
Предлагаю использовать поле `eleventyComputed` в data-файлах для получения этих данных. Таким образом, мы переносим логику в слой данных, где она и должна быть.
В некоторых своих проектах я перезатираю оригинальное поле computed-полем, то есть вместо, например, поля `author` с id автора будет подставляться объект с данными автора. Здесь заведены отдельные поля, например, `authorData` для явности.
Другими словами, такое поведение имитирует join'ы в SQL или _reference populate_ в MongoDB.
=> Использование `eleventyComputed` для получения данных о людях

src/styles/blocks/tooltip.css
На тачевых девайсах с произвольным зумом мог отрываться уголок от тултипа
=> Поправил отрывающуюся стрелку у тултипа

src/styles/blocks/archive.css, src/styles/blocks/content.css, src/styles/blocks/links.css, src/styles/blocks/menu.css, src/styles/blocks/not-found.css, src/styles/blocks/related-articles.css, src/styles/fonts.css
Здоровья!
Предлагаю использовать в дескрипторах `@font-face` свойство `font-stretch: expanded` для шрифтов _"Dewi Expanded"_.  Это позволит удалить явные указания `font-family: 'Dewi Expanded'` и управлять растяжением через `font-stretch: expanded`.
=> Использование `font-stretch: expanded` в дескрипторах `@font-face`

src/layouts/article.njk, src/styles/blocks/article.css, src/styles/blocks/creators.css
@akellbl4 уже делал правки в этом [MR#203](https://github.com/web-standards-ru/web-standards.ru/pull/203) для бага #192, но предлагаю другой подход.
Используется техника, эмулирующая container queries. Описана в статьях [Rémi Parmentier]() и [Heydon Pickering](https://heydonworks.com/article/the-flexbox-holy-albatross/). Метод позволяет отказаться от media queries и использовать для настройки всего лишь одного число - `--creators-breakpoint`.
Также сделал небольшие правки типографики, так как при длинных именах строки "слипаются".
Прикладываю скрины, что получилось (скроллбар возникает из-за `.article__heading-wrapper` - поправим позже):
<details>
<summary>скрины</summary>  
</details>
=> Правки адаптива блока с авторами.

src/styles/blocks/article-card.css
Если ширина экрана меньше 320px то переносим автора на новую строку.
Должно пофиксить #191 
Пример:
=> Фикс карточки статей для маленьких экранов

src/styles/blocks/content.css
В #156 надо было бы ещё и это медиа-выражение удалить.
Из-за него на десктопе подписи внутри `figure` отталкиваются на 60px.
=> Чистка недочищенного

src/styles/blocks/content.css
Вот [тут](https://web-standards.ru/articles/native-and-custom-select/) очень заметно, что подписи к картинкам стоят ближе к тексту, чем к самим картинкам. Нарушается принцип близости из дизайна. Давайте починим.
=> Ставит figcaption ближе к картинкам

src/pages/tag.njk
Упустил такой момент в прошлом PR: поскольку сейчас теги используются только для категорий статей, то и лишние фильтрации на странице `tag.njk` не нужны.
=> Пагинация только по коллекции `tagList` на странице тегов

src/includes/article-card.njk, src/layouts/article.njk, src/styles/blocks/article-card.css
Решение для #143.
Вроде бы всё основное сделала.
Единственное, что не могу нормально решить, — выравнивание имён и даты в обычных карточках на ширине вьюпорта с 800 и до 460, когда они выстраиваются рядом в две колонки. Колонка с именами располагается чуть ниже, чем дата. Я добавила для `span` с авторами обёртку `div`, что как раз и привело к этой проблеме. 
1) Это исправляет `line-height: 1` для блока-обёртки, но кажется, что это костыльное решение. К тому же, оно влияет на расстояние между элементами со `span`.
2) Второй вариант — `flex` или `inline-flex` для всё той же обёртки. Но тогда для детей нужно будет задавать отступы руками.
=> Поддержка 2–3 авторов

src/data/site.js, src/layouts/page.njk
В HTML страниц сайта есть ссылка на RSS статей, но нет RSS подкаста. Этот PR добавляет такую ссылку.
Вот примеры, как будет выглядеть парсинг RSS, когда мы указываем сам сайт `https://web-standards.ru`
<details>
<summary>Inoreader</summary>
</details>
<details>
<summary>Feedly</summary>
</details>
P.S.: Возможно, стоит поправить заголовок в репозитории подкаста, чтобы он лучше распознавался в сервисах, например "Веб-стандарты – Подкасты".
=> Добавляет ссылку на RSS-ленту подкаста как `<link rel="alternate" />`

src/articles/oklch-in-css-why-quit-rgb-hsl/index.md
В языковом сознании русскоговорящих людей `blue` может значить как голубой, так и синий.
=> Исправляет опечатку в статье про OKLCH

src/pages/episode.njk, src/scripts/modules/podcast.js, src/styles/blocks/player.css, src/styles/blocks/podcast.css, src/styles/styles.css
Fix #324
Долго игрался со стилями и так и не подобрал что-то, что могло бы нормально отображаться рядом с браузерным плеером в разных браузерах. Так что использовал минимум стилизации для кнопки.
Chrome:
Firefox:
=> Добавляет кнопки перемотки на 10 секунд

src/layouts/article.njk, src/styles/blocks/blob.css, src/styles/blocks/creators.css, src/styles/print.css
Правки:
- Задаёт одинаковые размеры атрибутов `width` и `height` для аватаров в статье. Видимо, ранее дизайн был другой и они остались
- Переносит `object-fit: cover` с контейнера, содержащего `img`, на само изображение `img`
- Удаляет лишние стили в `print.css`, так как декоративыне элементы аватарок больше не создаются с помощью псевдоэлементов
=> Правит аватары в статье

src/styles/blocks/content.css
Правки:
- Задаёт размер шрифта таким же, как у основного контента. Fix #291
- Удаляет `color: black`, так как этот цвет должен наследоваться от `.content`
=> Правит стили цитаты

eleventy.config.js
Для компонента `tooltip` создаётся дубликат атрибута `aria-label` в этих местах:
https://github.com/web-standards-ru/web-standards.ru/blob/307a1452adf7b1792694a6d799284bf0ca019a33/eleventy.config.js#L16-L18
https://github.com/web-standards-ru/web-standards.ru/blob/307a1452adf7b1792694a6d799284bf0ca019a33/src/helpers/markdown-it-anchor.js#L27-L28
Браузеры в инспекторе не показывают этот дубликат, но в HTML он остаётся и на него жалуется W3C HTML validator.
Оставил этот `aria-label` - "Копировать ссылку на заголовок"
=> Удаляет дубликат `aria-label` для кнопки копирования URL

eleventy.config.js
Вместо низкоуровнего API nunjucks с токенами/лексерами/парсерами предлагается ипользовать встроенный в Eleventy helper для shortcode'ов.
=> Упрощает задание shortcode для blob

src/includes/podcast-preview.njk, src/styles/blocks/podcast-preview.css
Правки:
- Удаляет элемент `.podcast-preview__meta` и переносит его стили на `.podcast-preview__date`
- Удаляет элемент `.podcast-preview__audio`, так как он не используется
- Оптимизирует число свойств для `.podcast-preview__link::after`
=> Упрощает структуру карточки-превью выпуска подкаста

src/styles/styles.css
Маркеры списка используют utf-8-символы, вставленные как есть, поэтому хорошо бы сообщить браузеру, что файл закодирован именно в этой кодировке.
Возможно, решит [эту проблему](https://github.com/web-standards-ru/web-standards.ru/issues/354), но это не точно.
=> Добавляет кодировку "utf-8" для CSS

src/scripts/modules/podcast.js
После выбора таймкода подкаст начинает проигрываться даже если не был изначально включен.
Такое поведение может напугать или оглушить, т.к. зачастую громкость браузерных звуков больше обычного. Так же в моём случае это мешает найти ссылку на материал по конкретной теме во время прослушивания подкаста на другом источнике.
Этот PR изменяет поведение таким образом, что при переходе между темами аудио воспроизводится только если изначально было включено.
=> Изменяет поведение при выборе темы подкаста

src/eleventy-config/transforms.js
Для новых трансформаций для заголовков я использовал `this.page.outputFileExtension` как признак принадлежности к тому или иному типу файла. По всей видимости, Eleventy использует его для custom template engine, когда авторы указывают расширение выходных файлов.
По умолчанию, `outputFileExtension` равен `html`, поэтому условие в трансформациях не выполняется и содержимое xml-файлов обрабатывается по правилам html, и, как следствие, появляются одиночные незакрытые теги.
Переделал на проверку `this.page.outputPath`.
=> Правит закрытие одиночных тегов в xml-фидах

src/data/eleventyComputed.js, src/includes/open-graph.njk, src/layouts/page.njk
Правки:
- Заметил, что в `layouts/page.njk` есть неиспользуемая переменная `isIndex`.
- Удалил использование `renderData.title`, так как нигде не нашёл места его задания. Видимо, было в начале редизайна.
- Перенёс задание переменной `titleSuffix` в глобальное computed-поле, чтобы в самих шаблонах было меньше вычислений. Конечное задание `title` также перенёс в computed-поле `pageTitle(data) { return data.title + data.titleSuffix; }`.
=> Рефакторит вывод `titleSuffix` и `title`

src/eleventy-config/transforms.js
Добавляет настройки, указанные в [этом комментарии](https://github.com/web-standards-ru/web-standards.ru/pull/374#issuecomment-2408852005).
С ними, HTML выглядит, например, так:
```html
<ul class="podcast__hosts-list"> <li class="podcast__host"> Вадим Макеев,</li> <li class="podcast__host"> Никита Дубко,</li> <li class="podcast__host"> Юлия Миоцен,</li> <li class="podcast__host"> Алексей Симоненко,</li> <li class="podcast__host"> Андрей Мелихов</li> </ul>
```
=> Меняет настройки HTML-минификатора для сохранения только значимых пробелов

package-lock.json, package.json
Сейчас есть такая проблема. Репозиторий подкаста загружается два раза при установке зависимостей. Один раз - так как он числится как зависимость, второй раз - в хуке `postinstall`, чтобы убедиться, что пришли новые данные, так как в `package-lock.json` может быть указатель на старые данные.
Предлагаю убрать явное упоминание подкаста как зависимости и оставить загрузку только в `postinstall`. Это позволит:
- загружать данные подкаста только один раз
- убрать "шум" в `package-lock.json` типа такого:  
Также увидел, что в `npm run build` была установка зависимостей. Как понял, это сделано, чтобы при локальных сборках всегда были новые данные подкаста? В любом случае, лучше вынести это оттуда и либо вызывать руками `npm run fetch-podcast-data && npm run build`, либо сделать для этого …
=> Рефакторит загрузку данных подкаста в npm

src/styles/blocks/content.css
Кнопка с тултипом в заголовках контента может переноситься отдельно:
При добавлении `text-wrap: balance` выглядит лучше:
=> Правит "висячие" кнопки тултипов в заголовках

src/styles/blocks/links.css, src/styles/blocks/main.css, src/styles/blocks/related-articles.css
Этот PR устраняет "прилипание" блока статей "Ещё" к футеру на размерах экрана 800-1024 (fix #272) и немного рефакторит стили с связанных блоках.
Другую часть issue, связанную с переполнением, нужно решать в рамках этой задачи https://github.com/web-standards-ru/web-standards.ru/issues/139.
=> Правит внешние отступы блока дополнительных статей

package-lock.json, package.json, src/eleventy-config/transforms.js
В библиотеке `sharp` была [особенность](https://github.com/11ty/eleventy-img/pull/182) с вычислением размеров для gif-изображений, которая правилась в этом [PR](https://github.com/web-standards-ru/web-standards.ru/pull/350).
Дополнительно `sharp` удалён из явных зависимостей, так как не используется больше напрямую, а тянется внутри `@11ty/eleventy-img`.
=> Удаляет хак для обхода бага для генерации gif
